# Popurarity Based Recommendation System

In [1]:
import numpy as np
import pandas as pd

In [2]:
movie_names = pd.read_csv("movies.csv")
movie_names.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [3]:
rating_data = pd.read_csv("ratings.csv")
rating_data.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [4]:
movie_data = pd.merge(rating_data, movie_names, on='movieId')

In [5]:
movie_data.head()

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama

# Criteria For Popularity Based Recommendation Systems
The criteria is based on:
1. Movies with the highest rating
2. Number of views

# Average ratings of movies

In [6]:
movie_data.groupby('title')['rating'].mean().head()

title
"Great Performances" Cats (1998)           1.750000
$9.99 (2008)                               3.833333
'Hellboy': The Seeds of Creation (2004)    2.000000
'Neath the Arizona Skies (1934)            0.500000
'Round Midnight (1986)                     2.250000
Name: rating, dtype: float64

# Ratings count

In [8]:
movie_data.groupby('title')['rating'].mean().sort_values(ascending=False).head(30)

title
Room, The (2003)                                                             5.0
Gentlemen of Fortune (Dzhentlmeny udachi) (1972)                             5.0
Germany Year Zero (Germania anno zero) (Deutschland im Jahre Null) (1948)    5.0
'night Mother (1986)                                                         5.0
George Carlin: You Are All Diseased (1999)                                   5.0
Get Carter (1971)                                                            5.0
10 Attitudes (2001)                                                          5.0
Zelary (2003)                                                                5.0
Z Channel: A Magnificent Obsession (2004)                                    5.0
Ghost of Frankenstein, The (1942)                                            5.0
16 Wishes (2010)                                                             5.0
Rustom (2016)                                                                5.0
Sacrifice, The (Offret - Sacraficatio) (1986)                                5.0
Saddest Music in the World, The (2003)                                       5.0
Bone Tomahawk (2015)                                                         5.0
Boiling Point (1993)                                                         5.0
Get Your Stuff (2000)                                                        5.0
Ghost in the Shell 2.0 (2008)                                                5.0
World of Tomorrow (2015)                                                     5.0
Eclisse, L' (Eclipse) (1962)                                                 5.0
Trailer Park Boys (1999)                                                     5.0
An Evening with Robin Williams (1982)                                        5.0
Eighteen (2005)                                                              5.0
King Is Alive, The (2000)                                                    5.0
Kidnapping, Caucasian Style (Kavkazskaya plennitsa) (1967)                   5.0
Kids in America (2005)                                                       5.0
Edge of Heaven, The (Auf der anderen Seite) (2007)                           5.0
Something Borrowed (2011)                                                    5.0
Touch of Pink (2004)                                                         5.0
Totally F***ed Up (1993)                                                     5.0
Name: rating, dtype: float64

# Rating Count

In [9]:
movie_data.groupby('title')['rating'].count().sort_values(ascending=False).head(30)

title
Forrest Gump (1994)                                                               341
Pulp Fiction (1994)                                                               324
Shawshank Redemption, The (1994)                                                  311
Silence of the Lambs, The (1991)                                                  304
Star Wars: Episode IV - A New Hope (1977)                                         291
Jurassic Park (1993)                                                              274
Matrix, The (1999)                                                                259
Toy Story (1995)                                                                  247
Schindler's List (1993)                                                           244
Terminator 2: Judgment Day (1991)                                                 237
Star Wars: Episode V - The Empire Strikes Back (1980)                             234
Braveheart (1995)                                                                 228
Back to the Future (1985)                                                         226
Fargo (1996)                                                                      224
American Beauty (1999)                                                            220
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    220
Independence Day (a.k.a. ID4) (1996)                                              218
Star Wars: Episode VI - Return of the Jedi (1983)                                 217
Aladdin (1992)                                                                    215
Fugitive, The (1993)                                                              213
Fight Club (1999)                                                                 202
Dances with Wolves (1990)                                                         202
Seven (a.k.a. Se7en) (1995)                                                       201
Usual Suspects, The (1995)                                                        201
Apollo 13 (1995)                                                                  200
Godfather, The (1972)                                                             200
Lion King, The (1994)                                                             200
Lord of the Rings: The Fellowship of the Ring, The (2001)                         200
True Lies (1994)                                                                  198
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)                                         196
Name: rating, dtype: int64

# Lets add the average rating count to our table

In [10]:
movie_data[['title', 'rating']]

                                                 title  rating
0                               Dangerous Minds (1995)     2.5
1                                         Dumbo (1941)     3.0
2                                      Sleepers (1996)     3.0
3                          Escape from New York (1981)     2.0
4       Cinema Paradiso (Nuovo cinema Paradiso) (1989)     4.0
...                                                ...     ...
99999                     Raising Victor Vargas (2002)     2.5
100000                                   Stevie (2002)     4.0
100001                     Matrix Reloaded, The (2003)     4.0
100002                              Whale Rider (2002)     2.5
100003                               Seabiscuit (2003)     3.5

[100004 rows x 2 columns]

# Calculate the average ratings

In [11]:
ratings_mean_count = pd.DataFrame(movie_data.groupby('title')['rating'].mean())
ratings_mean_count

                                             rating
title
"Great Performances" Cats (1998)           1.750000
$9.99 (2008)                               3.833333
'Hellboy': The Seeds of Creation (2004)    2.000000
'Neath the Arizona Skies (1934)            0.500000
'Round Midnight (1986)                     2.250000
...                                             ...
xXx (2002)                                 2.478261
xXx: State of the Union (2005)             1.000000
¡Three Amigos! (1986)                      3.258065
À nous la liberté (Freedom for Us) (1931)  4.500000
İtirazım Var (2014)                        3.500000

[9064 rows x 1 columns]

# Calculate the Count of the ratings and add to the AVERAGE RATINGS above

In [12]:
ratings_mean_count['rating_counts'] = pd.DataFrame(movie_data.groupby('title')['rating'].count())

In [13]:
ratings_mean_count

                                             rating  rating_counts
title
"Great Performances" Cats (1998)           1.750000              2
$9.99 (2008)                               3.833333              3
'Hellboy': The Seeds of Creation (2004)    2.000000              1
'Neath the Arizona Skies (1934)            0.500000              1
'Round Midnight (1986)                     2.250000              2
...                                             ...            ...
xXx (2002)                                 2.478261             23
xXx: State of the Union (2005)             1.000000              1
¡Three Amigos! (1986)                      3.258065             31
À nous la liberté (Freedom for Us) (1931)  4.500000              1
İtirazım Var (2014)                        3.500000              1

[9064 rows x 2 columns]

In [14]:
ratings_mean_count['rating'] = round(ratings_mean_count['rating'], 1)

In [16]:
ratings_mean_count.head()

                                         rating  rating_counts
title
"Great Performances" Cats (1998)            1.8              2
$9.99 (2008)                                3.8              3
'Hellboy': The Seeds of Creation (2004)     2.0              1
'Neath the Arizona Skies (1934)             0.5              1
'Round Midnight (1986)                      2.2              2

In [17]:
ratings_mean_count = ratings_mean_count[(ratings_mean_count['rating'] >4) & (ratings_mean_count['rating_counts'] >100)]
ratings_mean_count

                                                    rating  rating_counts
title
Amelie (Fabuleux destin d'Amélie Poulain, Le) (...     4.1            125
American Beauty (1999)                                 4.2            220
Apocalypse Now (1979)                                  4.1            112
Casablanca (1942)                                      4.2            117
Dark Knight, The (2008)                                4.2            121
Dr. Strangelove or: How I Learned to Stop Worry...     4.2            105
Eternal Sunshine of the Spotless Mind (2004)           4.1            106
Fargo (1996)                                           4.3            224
Fight Club (1999)                                      4.2            202
Forrest Gump (1994)                                    4.1            341
Godfather, The (1972)                                  4.5            200
Godfather: Part II, The (1974)                         4.4            135
Good Will Hunting (1997)                               4.1            157
Goodfellas (1990)                                      4.2            131
L.A. Confidential (1997)                               4.1            125
Lord of the Rings: The Fellowship of the Ring, ...     4.2            200
Lord of the Rings: The Return of the King, The ...     4.1            176
Lord of the Rings: The Two Towers, The (2002)          4.1            188
Léon: The Professional (a.k.a. The Professional...     4.1            132
Matrix, The (1999)                                     4.2            259
Memento (2000)                                         4.2            132
Monty Python and the Holy Grail (1975)                 4.2            145
One Flew Over the Cuckoo's Nest (1975)                 4.3            144
Princess Bride, The (1987)                             4.2            163
Pulp Fiction (1994)                                    4.3            324
Raiders of the Lost Ark (Indiana Jones and the ...     4.2            220
Reservoir Dogs (1992)                                  4.2            132
Schindler's List (1993)                                4.3            244
Shawshank Redemption, The (1994)                       4.5            311
Silence of the Lambs, The (1991)                       4.1            304
Stand by Me (1986)                                     4.1            112
Star Wars: Episode IV - A New Hope (1977)              4.2            291
Star Wars: Episode V - The Empire Strikes Back ...     4.2            234
Star Wars: Episode VI - Return of the Jedi (1983)      4.1            217
Taxi Driver (1976)                                     4.2            118
Trainspotting (1996)                                   4.1            124
Usual Suspects, The (1995)                             4.4            201

In [18]:
ratings_mean_count = ratings_mean_count.sort_values(by= 'rating', ascending=False).head(10)
ratings_mean_count

                                                    rating  rating_counts
title
Godfather, The (1972)                                  4.5            200
Shawshank Redemption, The (1994)                       4.5            311
Usual Suspects, The (1995)                             4.4            201
Godfather: Part II, The (1974)                         4.4            135
One Flew Over the Cuckoo's Nest (1975)                 4.3            144
Fargo (1996)                                           4.3            224
Schindler's List (1993)                                4.3            244
Pulp Fiction (1994)                                    4.3            324
Raiders of the Lost Ark (Indiana Jones and the ...     4.2            220
American Beauty (1999)                                 4.2            220

# These are the Top 10 Movies we Will recommend to our users just like netflix does (Obv THE GODFATHER is on TOP ! )